"""add_location_fields_to_company_experience

Revision ID: 3d096242daea
Revises: 924de1696ecd
Create Date: 2025-11-17 02:34:42.639556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d096242daea'
down_revision = '924de1696ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_experiences', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('company_experiences', sa.Column('municipality', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_experiences', 'municipality')
    op.drop_column('company_experiences', 'department')
    # ### end Alembic commands ###

