"""add_apertura_estado_field

Revision ID: 924de1696ecd
Revises: b5691693bd8f
Create Date: 2025-11-16 22:10:15.570520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924de1696ecd'
down_revision = 'b5691693bd8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('apertura_estado', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'apertura_estado')
    # ### end Alembic commands ###

