"""add_company_experience_table

Revision ID: b5691693bd8f
Revises: cdf22263da7b
Create Date: 2025-11-16 19:19:52.159166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5691693bd8f'
down_revision = 'cdf22263da7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('contracting_entity', sa.String(length=500), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('engineering_area', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_experiences_company_name'), 'company_experiences', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_experiences_company_name'), table_name='company_experiences')
    op.drop_table('company_experiences')
    # ### end Alembic commands ###

