"""Initial migration

Revision ID: c996d25d859b
Revises: 
Create Date: 2025-11-16 06:30:44.704917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c996d25d859b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('only_relevant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_active'), 'subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_subscriptions_contact_email'), 'subscriptions', ['contact_email'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('SECOP_I', 'SECOP_II', 'SECOP_INTEGRADO', name='tendersource'), nullable=False),
    sa.Column('entity_name', sa.String(length=500), nullable=False),
    sa.Column('object_text', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('process_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_relevant_interventoria_vial', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_external_id'), 'tenders', ['external_id'], unique=True)
    op.create_index(op.f('ix_tenders_is_relevant_interventoria_vial'), 'tenders', ['is_relevant_interventoria_vial'], unique=False)
    op.create_index(op.f('ix_tenders_publication_date'), 'tenders', ['publication_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_publication_date'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_relevant_interventoria_vial'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_external_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_subscriptions_contact_email'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_active'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###

