"""Add contract_type and contract_modality fields

Revision ID: cdf22263da7b
Revises: c996d25d859b
Create Date: 2025-11-16 07:27:54.403653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf22263da7b'
down_revision = 'c996d25d859b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('contract_type', sa.String(length=200), nullable=True))
    op.add_column('tenders', sa.Column('contract_modality', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'contract_modality')
    op.drop_column('tenders', 'contract_type')
    # ### end Alembic commands ###

